### ISSUE TITLE
Suggestion to remove UK region from hacs.json 

### ISSUE THREAD

**Issue by johntdyer** [robmarkcole/HASS-amazon-rekognition#18]
did you intend to have a region set in here, because that means it will only show up for clients using the default or UK regions. 

https://github.com/robmarkcole/HASS-amazon-rekognition/blob/master/hacs.json#L3

 I think that feature was intended for offerings that are infact region specific, like a trash collector that's UK only.  However since Amazon is globally available I would agree that you would want to omit that config in this case.  thoughts? 

FYI, this caught me off guard in https://github.com/hacs/integration/issues/950

**Comment by robmarkcole** [comment]
fixed, thanks
