### ISSUE TITLE
Rekognition Image Processing entity not found after updating to 1.6

### ISSUE THREAD

**Issue by roygbiv856** [robmarkcole/HASS-amazon-rekognition#31]
After installing 1.6 of rekognition, its image processing entity can no longer be found. I have just installed 1.7 with no change. I installed through HACS and am on the latest version of that too. I see scan interval is no longer a part of config.yaml, so I commented that out, but still doesn't work. Any ideas?

**Comment by My-userid** [comment]
1.6 didn't work for me either, so went back to 1.3.
In HA log I saw a long list of fails to install Pillow, which seems to be a new requirement.

I run HA in docker on my Synology DS918+.

**Comment by roygbiv856** [comment]
Im an idiot. I never realized you could downgrade with HACS. That fixed it! Thanks

**Comment by donnlee** [comment]
Might be related to issue #12 
Pls post any errors found in Dev Tools > Logs after a fresh restart of HA.

**Comment by robmarkcole** [comment]
Ive now pinned the pillow version, so this should be fixed
