### ISSUE TITLE
Incorrect version tag for breaking change

### ISSUE THREAD

**Issue by ping-localhost** [robmarkcole/HASS-amazon-rekognition#37]
@robmarkcole Please increase the major version the next time you do a breaking change release (like the `target` to `targets` change). That way you comply with semver and it makes it easier to spot for people, as I personally don't check changelogs if it's a feature bump, but will double check if it's a major.

**Comment by robmarkcole** [comment]
good point

**Comment by ping-localhost** [comment]
Thank you for the re-release. 👍
