### ISSUE TITLE
Only detect valid objects - Broke my node-red setup

### ISSUE THREAD

**Issue by wackerr** [robmarkcole/HASS-amazon-rekognition#53]
Hi,
After the release "Only detect valid objects" my node-red integration stopped to work as expected.
In my setup im not really using the targets at all. Instead use the labels and filter on their confidence.

Since I have various vehicles driving up to our house I have been using the label "vehicle" instead of car(since car label will not cover trucks etc). After this change it seems like vehicle is sorted out as "fluffy".

Is it possible to revert back and have all labels in there. Or maybe a configuration item?
I can see other use cases for labels that maybe dont have the bounding box around them.

Thanks
Stefan

**Comment by robmarkcole** [comment]
I agree it’s useful to have the label, and will think how best to include it, probably when I add events
