### ISSUE TITLE
Include label in attributes

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-amazon-rekognition#56]
Since this can be useful

Ref https://github.com/robmarkcole/HASS-amazon-rekognition/issues/53

**Comment by robmarkcole** [comment]
The challenge here is that an object can have multiple labels, meaning a user will have to apply complex yaml to iterate over them:
```
'Parents': [{'Name': 'Vehicle'}, {'Name': 'Transportation'}]}]
```

**Comment by robmarkcole** [comment]
Could go back to the previous implementation of having lables and their confidence listed, but that will make the code more complex and harder to maintain

**Comment by wackerr** [comment]
Really happy that this integration is worked on and gets improved so I dont want to make it harder to maintain but the previous implementation was much easier to work with as described above. Will use the earlier version for production and look into if I in a good way can work with the latest version.

**Comment by robmarkcole** [comment]
I recall you were using vehicle to detect cars and others, you can just use a list of common vehicles instead? I do appreciate that it’s useful to not have to specify exactly what kind of vehicle.

I am interested in your use case, is it commercial?

**Comment by robmarkcole** [comment]
@wackerr please tryout `master` which now includes labels. I think this is backwards compatible with how you were using the labels.

**Comment by wackerr** [comment]
@robmarkcole 
Its getting there but was easier in the earlier implementations.
This is what I see in HA:
labels: 
- name: human
  confidence: 99.858
- name: path
  confidence: 90.703
- name: clothing
  confidence: 88.022

In node-red its shows as an array like this:
labels: array[22]
[0 … 9]
0: object
name: "human"
confidence: 99.858
1: object
name: "path"
confidence: 90.703
2: object
name: "clothing"
confidence: 88.022

In your example it shows the label and the confidence on one string and in the last version its two strings? One string would have been easier but I guess I can learn how to use it.

Also each label shows up as object 0, object 1 etc in the array so I also need to "search" for the right object number.

Lastly I dont think the targets shows up in the list of labels? For example I got label "person" as a target and it gets the bounding box. But its not in the list of labels.

Maybe I just need to get better at JSON :)

I use node-red for all automations and got all my logic there. For example I want to be able to do certain tasks based on the confidence level and want to avoid doing multiple requests to Amazon.

You asked earlier if this use case was for commercial. I use it for my home but also for my parents and they run a car repair shop at the same location as their home. Handy to get notification if there is a delivery truck arriving when they have lunch etc.

**Comment by robmarkcole** [comment]
I recommend trying to use the newly added events, rather than crawling the attributes. Let me know how you get on!

**Comment by HITChris** [comment]
@wackerr - I'm referencing a specific labels array repetition like so: aws_data.attributes.labels[name='person'].confidence

Also, default target 'person' is showing up in the label array for me.

**Comment by wackerr** [comment]
@HITChris Will test the referncing out. 
Regarding the labels I have not tested with the default but for example I get "car count"=1 but car does not turn up in the labels list.

@robmarkcole I had a look at it and will play around with it. One issue I see is that rekognition.object_detected and rekognition.label_detected is that there is no reference to the HA entity for the camera. So I cannot for sure match the camera name with the event in my flow.
There might be an event for another camera in around the same time. Is it possible to add the rekognition entity in the event? In my case  image_processing.rekognition_dwa

**Comment by robmarkcole** [comment]
Created https://github.com/robmarkcole/HASS-amazon-rekognition/issues/65
