### ISSUE TITLE
Python code not tied to Home Assistant

### ISSUE THREAD

**Issue by mpovolo** [robmarkcole/HASS-amazon-rekognition#69]
Would you have the python code that is not tied to Home Assistant.  I would like to use this same code for multiple cameras off a Raspberry Pi and not impact processing on Home Assistant.  Probably could go into the existing code and modify it but hoping you have something.  I have Amazon Rekognition code that returns the objects found, but I like this one as it returns an image with bounded boxes.
thanks

**Comment by robmarkcole** [comment]
You could certainly create that from this codebase, but this is not something I am willing to do myself
