### ISSUE TITLE
"Unknown" image processing entities after 2.6 update

### ISSUE THREAD

**Issue by roygbiv856** [robmarkcole/HASS-amazon-rekognition#70]
I went from 2.3 I think straight to 2.6 and my rekognition entities say "unknown". I've updated HACS to the most current version and im on home assistant .111. I've tried downgrading rekognition to 2.5, 2.4, and 2.3, but the entities still say "unknown". Ive made the necessary changes in my config.yaml for the new "targets", but im still out of luck. Any ideas?

**Comment by jtscott** [comment]
Having similar issue on 0.113 today

```
Logger: homeassistant.config
Source: config.py:800
First occurred: 11:30:11 AM (1 occurrences)
Last logged: 11:30:11 AM

Platform error: image_processing - Requirements for amazon_rekognition not found: ['pillow==7.1.1'].
```

**Comment by roygbiv856** [comment]
@jtscott where exactly are you finding this log info?

**Comment by robmarkcole** [comment]
see https://github.com/robmarkcole/HASS-amazon-rekognition/issues/71
