### ISSUE TITLE
Bump pillow

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-amazon-rekognition#71]
HA again bumped pillow: `pillow==7.1.2`
Need to make even

**Comment by roygbiv856** [comment]
Im a little confused. Is this something you have to do on your end and we just have to wait for an update or is this some kind of change I can make in my configuration now somehow?

**Comment by robmarkcole** [comment]
You can manually update manifest.json if you want to yes

**Comment by goncalvespedro** [comment]
Thanks Rob, changing manifest.json pillow==7.1.1 --> pillow==7.1.2 fixed it :)

**Comment by roygbiv856** [comment]
It didnt work for me. I have never been able to get manual install to work. There's very few steps and they seem dead simple, but ive only had success installing through HACS. Guess ill wait for the update through that. Thanks for all your work on this. Its easily my favorite thing ive implemented in HA!

**Comment by robmarkcole** [comment]
resolved in release 2.7

**Comment by roygbiv856** [comment]
You're a gentleman and a sir, Mr Cole! Unfortunately, the problem has not gone away. I've tried several versions of your integration on both HA .112 and .113. Ive also tried many small changes to my config.yaml and no luck. The only error i can see in the HA logs is:

- Logger: homeassistant.helpers.service
- Source: helpers/service.py:189
- First occurred: 8:46:47 AM (4 occurrences)
- "Unable to find referenced entities image_processing.rekognition_person_fy1"

**Comment by robmarkcole** [comment]
@roygbiv856 please raise on the HA forums as I doubt this is a code issue. IF it does have a code origin please create a new issue. Thanks

**Comment by roygbiv856** [comment]
@robmarkcole Im an idiot. The entity states show unknown until a scan is made. Thanks again for all the great work on this bad boy
