### ISSUE TITLE
not saving image

### ISSUE THREAD

**Issue by alexandrechoske** [robmarkcole/HASS-amazon-rekognition#76]
hi guys.

First time i did the image processing, the image saved.

But now is not saving anymore, any clue?

`- platform: amazon_rekognition
  aws_access_key_id: 
  aws_secret_access_key: 
  region_name: eu-west-1 # optional region, default is us-east-1
  save_file_folder: /config/www/amazon-rekognition/ # Optional image storage
  save_timestamped_file: True # Set True to save timestamped images, default False
  confidence: 90 # Optional, default is 80 percent
  targets: # Optional target objects, default person
    - person
  roi_x_min: 0.6 # optional, range 0-1, must be less than roi_x_max
  roi_x_max: 0.8 # optional, range 0-1, must be more than roi_x_min
  roi_y_min: 0.4 # optional, range 0-1, must be less than roi_y_max
  roi_y_max: 0.8 # optional, range 0-1, must be more than roi_y_min
  source:
    - entity_id: camera.casa_sogros_frente_porta`

**Comment by robmarkcole** [comment]
please use forums
