### ISSUE TITLE
self._targets_found not used in annotation

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-amazon-rekognition#77]
`self._targets_found` is the list of targets filtered by confidence etc, but this is not used by `self.save_image`, resulting in all targets being plotted regardless of confidence. The fix is to pass `self._targets_found` to `self.save_image`

CC @majkers

**Comment by robmarkcole** [comment]
Alright I remember the reason for this was that we would still show objects that are outside the ROI. 

![image](https://user-images.githubusercontent.com/11855322/105944720-cb0f4c80-605b-11eb-9b08-02b360c90cd3.png)

**Comment by majkers** [comment]
In my picture all are in red boxes...

**Comment by robmarkcole** [comment]
closed in https://github.com/robmarkcole/HASS-amazon-rekognition/releases/tag/v3.0
